### ISSUE TITLE
Fulfil the open-source checklist

### ISSUE THREAD

**Issue by elbrujohalcon** [inaka/emarkdown#2]
## General Items
- [x] It has a github repo
- [x] It has a proper Apache2 LICENSE file.
- [ ] It's has a clear and useful README.md
- [ ] It's documented (with examples)
- [ ] It's tested.
- [x] It's hooked to the [open-source hipchat room](http://inaka.net/hipchat)
- [ ] It has a link to the [open-source hipchat room](http://inaka.net/hipchat) in its README.
- [ ] It has a link to [inaka.github.io](http://inaka.github.io) in its README and/or landing page.

## For Libraries
- [ ] Examples of use are documented in the README or linked from there.

## For Erlang Projects
- [ ] It follows the rules for our [Project Setup](ERLANG.md#project-setup):
      · proper rebar.config
      · rebar3 `compile`, `dialyzer`, `doc` and `ct` work with **no warnings**
      · `deps` coming from hex.pm
      · `elvis.config` up to date.
      · Meta testing in place.
      · proper data for hex.pm on app.src

## For Erlang/Elixir Projects
- [x] It's checked with [Gadget](http://gadget.inakalabs.com)
- [ ] It's published on [Hex.pm](https://hex.pm)
